# Generated by Django 4.2.2 on 2023-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='1006. Известна денежная сумма. Разменять её купюрами 500, 100, 10 и монетой 2 руб., если это возможно.', max_length=255, verbose_name='Формулировка задачи')),
                ('S', models.IntegerField(default=0, verbose_name='Денежная сумма')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': 'S',
                'verbose_name_plural': 'S',
                'ordering': ('-id', '-S'),
            },
        ),
        migrations.DeleteModel(
            name='AlgoTask',
        ),
    ]
